config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'base/index'
    resources :authors
    resources :users
    resources :publishers, except: [:new]
    resources :books, except: [:new]
  end

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'

  root 'catalogs#index'

  get '/add_publisher', to: 'admin/publishers#new', as: 'add_publisher'
  get '/add_book', to: 'admin/books#new', as: 'add_book'
  get '/signup', to: 'users#new', as: 'signup'
  get '/reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'
  

  resources :books, only: [:show]
  resources :users, only: [:create, :show]
  resource :session, only: [:destroy]
  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]
  
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications, dependent: :destroy
  has_many :authors, through: :publications

  validates :title, presence: true
  validates :isbn, presence: true
  validates :description, presence: true
  validates :published_at, presence: true
  validates :publisher_id, presence: true
  validates :page_count, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }

  mount_uploader :book_cover, BookCoverUploader
  
  def self.search_by_title(title)
    where('title LIKE ?', "%#{title}%").order(:title)
  end  
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :set_book, except: [:index, :new, :create]

  def index
    @books = Book.all
  end

  def show
  end
  
   def new
    @book = Book.new
    @book.publications.build

    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = 'Book has been created.'
      redirect_to [:admin, @book]
    else
      flash.now[:danger] = 'Book has not been created.'
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
      @publishers = Publisher.all
      @authors = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = 'Book has been updated.'
      redirect_to [:admin, @book]
    else
      flash[:danger] = 'Book has not been updated.'
      @publishers = Publisher.all
      @authors = Author.all
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = 'Book has been deleted.'
      redirect_to admin_books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :isbn, :page_count, :price, :description, :book_cover,
                                   :published_at, :publisher_id, author_ids: [])
    end

    def set_book
      @book = Book.find(params[:id])
    end
end

app/views/admin/books/_form.html.erb
<%= bootstrap_form_for([:admin, @book], :html => {multipart: true, class: "form-horizontal", role: "form"}) do |f| %>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Title</label>
    <div class='col-sm-9'>
      <%= f.text_field :title, class: 'form-control', hide_label: true, placeholder: 'Title of the book', autofocus: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Isbn</label>
    <div class='col-sm-9'>
      <%= f.text_field :isbn, class: 'form-control', hide_label: true, placeholder: 'Book ISBN' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Page count</label>
    <div class='col-sm-9'>
      <%= f.text_field :page_count, class: 'form-control', hide_label: true, placeholder: 'Number of pages' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Price</label>
    <div class='col-sm-9'>
      <%= f.text_field :price, class: 'form-control', hide_label: true, placeholder: 'Book unit price' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Description</label>
    <div class='col-sm-9'>
      <%= f.text_area :description, class: 'form-control', hide_label: true, placeholder: 'Book description' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publication date</label>
    <div class='col-sm-9'>
      <%= f.text_field :published_at, placeholder: 'Date format: yyyy-mm-dd', class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publisher</label>
    <div class='col-sm-9'>
      <%= f.select :publisher_id, @publishers.map { |p| [p.name, p.id] },
                      prompt: 'Select a publisher', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Book cover</label>
    <div class='col-sm-9'>
      <%= f.file_field :book_cover, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Authors</label>
    <div class='col-sm-9'>
      <%= f.collection_check_boxes :author_ids, @authors, :id, :full_name, class: 'form-control', hide_label: true %>
    </div>
  </div>
 
  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/books/_form0.html.erb
<%= bootstrap_form_for(@book, :html => {:class => "form-horizontal"}) do |f| %>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Title</label>
    <div class='col-sm-9'>
      <%= f.text_field :title, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Isbn</label>
    <div class='col-sm-9'>
      <%= f.text_field :isbn, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Page count</label>
    <div class='col-sm-9'>
      <%= f.text_field :page_count, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Price</label>
    <div class='col-sm-9'>
      <%= f.text_field :price, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Description</label>
    <div class='col-sm-9'>
      <%= f.text_area :description, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Published at</label>
    <div class='col-sm-9'>
      <%= f.text_field :published_at, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publisher</label>
    <div class='col-sm-9'>
      <%= f.select :publisher_id, Publisher.all.map { |p| [p.name, p.id] },
                      prompt: 'Select a publisher', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Book cover</label>
    <div class='col-sm-9'>
      <%= f.file_field :book_cover, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <%= f.fields_for :publications do |pub| %>
    <div class='form-group' id='authors'>
      <label class='control-label col-sm-3'>Author</label>
      <div class='col-sm-9'>
        <%= pub.select :author_id, options_for_select(Author.all.collect { |a| [a.full_name, a.id] }),
                          prompt: 'Select an author', class: 'form-control', hide_label: true  %>
      </div>
    </div>
  <% end %>
<!--
  <div class='form-group' id='authors'>
    <%= render partial: 'publications/publication' %>
  </div>
-->
  <div class='col-sm-9'>
    <%#= link_to 'Add another author', 'javascript:', id: 'add-author' %>
    <%= link_to 'Add another author', new_publication_path, remote: true,
                    update: 'authors', position: 'after', id: 'add-author' %>
  </div>
  <%# end %>
  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h3 class='titles'>Editing <%= "(#book.title)"%><h3>
  <div class='row'>
    <div class='col-md-11'>
      <%= render 'form'%>
    </div>
  </div>

app/views/admin/books/index.html.erb
<section>
  <header>
    <% if @books.empty? %>
      <h3>No Books Defined</h3>
    <% else %>
      <h3 class="titles">All Books</h3>
    <% end %>
  </header>
  <% @books.each do |book| %>
    <p class='book-title'>
      <%= link_to book.title, [:admin, book] %><br>
      <span class='price-class'><%= number_to_currency(book.price) %></span>
    </p>
    <p class='book-image'><%= image_tag(book.book_cover_url(:thumb)) if book.book_cover? %></p>
    <div>
      <hr>
    </div>
  <% end %>
  <br>
  <p><%= link_to 'Add New book', add_book_path, class: 'btn btn-primary' %></p>
</section>

app/views/admin/books/new.html.erb
<h3 class='titles'> Adding New Book</h3>
  <div class='row'>
    <div class='col-md-11'>
      <%= render 'form' %>
    </div>
  </div>

app/views/admin/books/search.html.erb
<!-- <article>
  <div class="row">
    <% @books.each do |book| %>
      <label class='col-sm-9'><%= book.title %></label><br>
      <div class="col-sm-4">
        <%= link_to image_tag(book.book_cover_url(:thumb)), book %>
      </div>
    <% end %>
  </div>
</article> -->

app/views/admin/books/show.html.erb
<section>
  <div class='row'>
    <div class='col-sm-12 cartless'>
      <header class='col-sm-12'>
        <h3 class='titles' id='book-show'><%= "#{@book.title}" %>'s Details</h3>
      </header>
      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>ISBN:</strong>
        </div>
        <div class='col-sm-9'>
          <%= @book.isbn %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Page count:</strong>
        </div>
        <div class='col-sm-9'>
          <%= @book.page_count %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Price:</strong>
        </div>
        <div class='col-sm-9'>
          <%= number_to_currency(@book.price) %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Description:</strong>
        </div>
        <div class='col-sm-9'>
          <%= @book.description %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Publisher:</strong>
        </div>
        <div class='col-sm-9'>
          <%= @book.publisher.name %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Published at:</strong>
        </div>
        <div class='col-sm-9'>
          <%= @book.published_at %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>

      <div class='col-sm-12'>
        <div class='col-sm-3'>
          <strong>Book cover:</strong>
        </div>
        <div class='col-sm-9'>
          <%= image_tag(@book.book_cover_url) if @book.book_cover? %>
        </div>
      </div>
      <div class='col-sm-12'>
        <hr>
      </div>
    </div>
  </div>
</section>

<% content_for(:sidebar) do %>
  <h4 class='cartless'>Actions</h4>
  <hr class='sidebar-hr'>
  <ul class='sidebar-link'>
    <li><%= link_to 'Edit', [:edit, :admin, @book], class: 'btn btn-danger btnwidth' %></li>
    <li><%= link_to 'Delete', [:admin, @book], method: :delete, class: 'btn btn-danger btnwidth',
        data: { confirm: "Are you sure you want to delete #{@book.title}?"} %></li>
  </ul>
  <hr class='sidebar-hr'>
<% end %>

app/views/admin/books/show0.html.erb
<section class='container'>
  <div class='row'>
    <div class='col-sm-8 col-sm-offset-1'>
      <header>
        <h3 class='titles' id='book-show'><%= "#{@book.title}" %>'s Details</h3>
      </header>
      <table class='table table-shift'>
        <tr>
          <td><strong>ISBN:</strong></td>
          <td><%= @book.isbn %></td>
        </tr>
        <tr>
          <td><strong>Page count:</strong></td>
          <td><%= @book.page_count %></td>
        </tr>
        <tr>
          <td><strong>Price:</strong></td>
          <td><%= number_to_currency(@book.price) %></td>
        </tr>
        <tr>
          <td><strong>Description:</strong></td>
          <td><%= @book.description %></td>
        </tr>
        <tr>
          <td><strong>Publisher:</strong></td>
          <td><%= @book.publisher.name %></td>
        </tr>
        <tr>
          <td><strong>Published at:</strong></td>
          <td><%= @book.published_at %></td>
        </tr>
        <% @book.authors.each do |author| %>
          <tr>
            <td><strong>Author:</strong></td>
            <td><%= author.full_name %></td>
          </tr>
        <% end %>
        <tr>
          <td><strong>Book cover:</strong></td>
          <td><%= image_tag(@book.book_cover_url) if @book.book_cover? %></td>
        </tr>
      </table>
    </div>
  </div>
</section>

<% content_for(:sidebar) do %>
  Actions
  <hr class='sidebar-hr'>
  <ul class='sidebar-link'>
    <li><%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-warning btnwidth' %></li>
    <li><%= link_to 'Delete', book_path(@book), method: :delete, class: 'btn btn-warning btnwidth',
        data: { confirm: "Are you sure you want to delete #{@book.title}?"} %></li>
  </ul>
  <hr class='sidebar-hr'>
<% end %>