config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'base/index'
    resources :authors
    resources :users
    resources :publishers, except: [:new]
    resources :books, except: [:new]
  end

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'

  root 'catalogs#index'

  get '/add_publisher', to: 'admin/publishers#new', as: 'add_publisher'
  get '/add_book', to: 'admin/books#new', as: 'add_book'
  get '/signup', to: 'users#new', as: 'signup'
  get '/reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'
  

  resources :books, only: [:show]
  resources :users, only: [:create, :show]
  resource :session, only: [:destroy]
  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]
  
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end
  
end

app/views/shared/_footer.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10 col-md-offset-1 footer'>
      <footer role="contentinfo">
        <p><small>Copyright &copy; 2015</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav role="navigation" class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bookstore App", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <% if current_user && current_user.admin? %>
              <li class="active"><%= link_to "Authors", admin_authors_path %></li>
              <li><%= link_to "Publishers", admin_publishers_path %></li>
              <li><%= link_to "Books", admin_books_path %></li>
              <li><%= link_to "Users", admin_users_path %></li>
            <% end %>
              <li><%= link_to "Catalogs", catalogs_path %></li>
            <% unless current_user %>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to "Sign in", signin_path %></li>
            <% else %>
              <li><%= link_to "Sign out", session_path, method: :delete %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
 <div class='container'>
    <%= render 'shared/messages' %>
    <div class='row'>

      <div class='col-md-9'>
        <% if content_for?(:sidebar) %>
          <div class='col-md-4 left'>
            <div id= 'left-content'>
              <%= yield :sidebar %>
            </div>
          </div>
          <div class='col-md-8 inner'>
            <div id='right-content'>
              <%= yield %>
            </div>
          </div>
        <% else %>
          <div class='col-md-10 col-md-offset-1 inner'>
            <div class='right-content'>
              <%= yield %>
            </div>
          </div>
        <% end %>
      </div>

      <div class='col-md-3'>
        <div id="cart">
          <%= render @cart if @cart %>
        </div>
      </div>

    </div>
  </div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href='#' class='close' data-dismiss='alert' &#215;></a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>