config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'base/index'
    resources :authors
    resources :users
    resources :publishers, except: [:new]
    resources :books, except: [:new]
  end

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'

  root 'catalogs#index'

  get '/add_publisher', to: 'admin/publishers#new', as: 'add_publisher'
  get '/add_book', to: 'admin/books#new', as: 'add_book'
  get '/signup', to: 'users#new', as: 'signup'
  get '/reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'
  

  resources :books, only: [:show]
  resources :users, only: [:create, :show]
  resource :session, only: [:destroy]
  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]
  
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :orders

  validates :first_name, :last_name, :email, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i }

  has_secure_password

  before_create :generate_token
  
  accepts_nested_attributes_for :addresses

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
  
  def to_param
    token
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
    
  end

  def new
    @user = User.new
  end

  def create
    passwd = params[:user][:password]
    usr_params = user_params.merge(password_confirmation: passwd)

    @user = User.new(usr_params)
    if @user.save
      flash[:success] = 'User has been created.'
      redirect_to [:admin, @user]
    else
      flash.now[:danger] = 'User has not been created.'
      render :new
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      flash[:success] = 'User has been updated.'
      redirect_to [:admin, @user]
    else
      flash[:danger] = 'User has not been updated.'
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = 'User has been deleted.'
      redirect_to admin_users_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                   :password_confirmation)
    end

    def set_user
      @user = User.find_by(token: params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def show
  end

  def new
    @user = User.new
    @user.addresses.build
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User has been created.'
      redirect_to signin_path
    else
      flash[:danger] = 'User has not been created.'
      render :new
    end
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
                                  addresses_attributes: [:address_line1, :address_line2, :city, :zipcode])
  end
end

app/views/admin/users/_form.html.erb
 <%= bootstrap_form_for [:admin, @user], :html => {:class => "form-horizontal"} do |f| %>
        <div class='form-group'>
          <label class='control-label col-sm-3'>First name</label>
          <div class='col-sm-9'>
            <%= f.text_field :first_name, class: 'form-control', hide_label: true %>
          </div>
        </div>
        <div class='form-group'>
          <label class='control-label col-sm-3'>Last name</label>
          <div class='col-sm-9'>
            <%= f.text_field :last_name, class: 'form-control', hide_label: true %>
          </div>
        </div>
        <div class='form-group'>
          <label class='control-label col-sm-3'>Email</label>
          <div class='col-sm-9'>
              <%= f.text_field :email, class: 'form-control', hide_label: true %>
          </div>
        </div>
        <div class='form-group'>
          <label class='control-label col-sm-3'>Password</label>
          <div class='col-sm-9'>
              <%= f.password_field :password, class: 'form-control', hide_label: true %>
          </div>
        </div>
        <hr>
        <div class='form-group actions control-group'>
          <div class='col-sm-offset-3'>
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
<% end %>

app/views/admin/users/edit.html.erb
<h3 class="titles"> Adding New User</h3>
  <div class='row'>
    <div class='col-md-10'>
      <%= render 'form' %>
    </div>
  </div>

app/views/admin/users/index.html.erb
<section>
  <header>
    <% if @users.empty? %>
      <h3>No Users Created</h3>
    <% else %>
      <h3 class="titles">All Users</h3>
    <% end %>
  </header>
  <div class='col-sm-10'>
    <% @users.each do |user| %>
      <div class='col-sm-8 col-sm-offset-2 user-list'>
        <%= link_to user.email, admin_user_path(user) %>
      </div>
      <br>
    <% end %>

    <div class='col-sm-offset-2' id='new-user-link'>
      <%= link_to 'Add New user', new_admin_user_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <br>
</section>

app/views/admin/users/new.html.erb
<h3 class="titles">Adding New User</h3>
  <div class="row">
    <div class="col-md-10">
      <%= render 'form'%>
    </div>
  </div>

app/views/admin/users/show.html.erb
<section>
  <div class='row details'>
    <div class='col-sm-10 col-sm-offset-1 cartless'>
      <header>
        <h3 class='titles'><%= "#{@user.full_name}" %>'s Profile</h3>
        <hr class='col-sm-12'>
      </header>

      <div class='col-sm-12'>
        <strong class='col-sm-4'>First name</strong>
        <div class='col-sm-8'>
          <%= @user.first_name %>
        </div>
      </div>
      <div class='col-sm-12'>
        <strong class='col-sm-4'>Last name</strong>
        <div class='col-sm-8'>
          <%= @user.last_name %>
        </div>
      </div>
      <div class='col-sm-12'>
        <strong class='col-sm-4'>Email</strong>
        <div class='col-sm-8'>
          <%= @user.email %>
        </div>
      </div>
    </div>
    <br/>
  </div>
</section>

<% content_for(:sidebar) do %>
  <h4 class='cartless'>Actions</h4>
  <hr class='sidebar-hr'>
  <ul class='sidebar-link'>
    <li><%= link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-default btnwidth' %></li>
    <li><%= link_to 'Delete', admin_user_path(@user), method: :delete, class: 'btn btn-default btnwidth',
        data: { confirm: "Are you sure you want to delete #{@user.full_name}?"} %></li>
  </ul>
  <hr class='sidebar-hr'>
<% end %>